// Generated by CIRCT firtool-1.62.0
module multiplier(
  input         clock,
                reset,
  input  [7:0]  io_inputA_0,
                io_inputB_0,
  output [15:0] io_output_0
);

  reg [15:0] io_output_0_REG;
  always @(posedge clock) begin
    if (reset)
      io_output_0_REG <= 16'h0;
    else
      io_output_0_REG <=
        {{8{io_inputA_0[7]}}, io_inputA_0} * {{8{io_inputB_0[7]}}, io_inputB_0};
  end // always @(posedge)
  assign io_output_0 = io_output_0_REG;
endmodule

