// Generated by CIRCT firtool-1.62.0
module group_processing_element_15(
  input         clock,
                reset,
  input  [7:0]  io_inputA_0,
                io_inputB_0,
                io_inputB_1,
                io_inputB_2,
                io_inputB_3,
  input         io_propagateB_0,
  output [7:0]  io_outputB_0,
                io_outputB_1,
                io_outputB_2,
                io_outputB_3,
  output [15:0] io_outputC_0,
                io_outputC_1,
                io_outputC_2,
                io_outputC_3
);

  wire [15:0] _vectorProcessingElementVector_0_3_io_outputC;
  wire [15:0] _vectorProcessingElementVector_0_2_io_outputC;
  wire [15:0] _vectorProcessingElementVector_0_1_io_outputC;
  wire [15:0] _vectorProcessingElementVector_0_0_io_outputC;
  reg  [15:0] io_outputC_0_REG;
  reg  [15:0] io_outputC_1_REG;
  reg  [15:0] io_outputC_2_REG;
  reg  [15:0] io_outputC_3_REG;
  always @(posedge clock) begin
    if (reset) begin
      io_outputC_0_REG <= 16'h0;
      io_outputC_1_REG <= 16'h0;
      io_outputC_2_REG <= 16'h0;
      io_outputC_3_REG <= 16'h0;
    end
    else begin
      io_outputC_0_REG <= _vectorProcessingElementVector_0_0_io_outputC;
      io_outputC_1_REG <= _vectorProcessingElementVector_0_1_io_outputC;
      io_outputC_2_REG <= _vectorProcessingElementVector_0_2_io_outputC;
      io_outputC_3_REG <= _vectorProcessingElementVector_0_3_io_outputC;
    end
  end // always @(posedge)
  processing_element vectorProcessingElementVector_0_0 (
    .clock         (clock),
    .reset         (reset),
    .io_inputA_0   (io_inputA_0),
    .io_inputB_0   (io_inputB_0),
    .io_propagateB (io_propagateB_0),
    .io_outputB_0  (io_outputB_0),
    .io_outputC    (_vectorProcessingElementVector_0_0_io_outputC)
  );
  processing_element vectorProcessingElementVector_0_1 (
    .clock         (clock),
    .reset         (reset),
    .io_inputA_0   (io_inputA_0),
    .io_inputB_0   (io_inputB_1),
    .io_propagateB (io_propagateB_0),
    .io_outputB_0  (io_outputB_1),
    .io_outputC    (_vectorProcessingElementVector_0_1_io_outputC)
  );
  processing_element vectorProcessingElementVector_0_2 (
    .clock         (clock),
    .reset         (reset),
    .io_inputA_0   (io_inputA_0),
    .io_inputB_0   (io_inputB_2),
    .io_propagateB (io_propagateB_0),
    .io_outputB_0  (io_outputB_2),
    .io_outputC    (_vectorProcessingElementVector_0_2_io_outputC)
  );
  processing_element vectorProcessingElementVector_0_3 (
    .clock         (clock),
    .reset         (reset),
    .io_inputA_0   (io_inputA_0),
    .io_inputB_0   (io_inputB_3),
    .io_propagateB (io_propagateB_0),
    .io_outputB_0  (io_outputB_3),
    .io_outputC    (_vectorProcessingElementVector_0_3_io_outputC)
  );
  assign io_outputC_0 = io_outputC_0_REG;
  assign io_outputC_1 = io_outputC_1_REG;
  assign io_outputC_2 = io_outputC_2_REG;
  assign io_outputC_3 = io_outputC_3_REG;
endmodule

