// Generated by CIRCT firtool-1.62.0
module pre_processor_b(
  input        clock,
               reset,
  input  [7:0] io_input_0,
               io_input_1,
               io_input_2,
               io_input_3,
               io_input_4,
               io_input_5,
               io_input_6,
               io_input_7,
               io_input_8,
               io_input_9,
               io_input_10,
               io_input_11,
               io_input_12,
               io_input_13,
               io_input_14,
               io_input_15,
               io_input_16,
               io_input_17,
               io_input_18,
               io_input_19,
               io_input_20,
               io_input_21,
               io_input_22,
               io_input_23,
               io_input_24,
               io_input_25,
               io_input_26,
               io_input_27,
               io_input_28,
               io_input_29,
               io_input_30,
               io_input_31,
  output [7:0] io_output_0,
               io_output_1,
               io_output_2,
               io_output_3,
               io_output_4,
               io_output_5,
               io_output_6,
               io_output_7,
               io_output_8,
               io_output_9,
               io_output_10,
               io_output_11,
               io_output_12,
               io_output_13,
               io_output_14,
               io_output_15,
               io_output_16,
               io_output_17,
               io_output_18,
               io_output_19,
               io_output_20,
               io_output_21,
               io_output_22,
               io_output_23,
               io_output_24,
               io_output_25,
               io_output_26,
               io_output_27,
               io_output_28,
               io_output_29,
               io_output_30,
               io_output_31
);

  reg [7:0] io_output_0_REG;
  reg [7:0] io_output_1_REG;
  reg [7:0] io_output_2_REG;
  reg [7:0] io_output_3_REG;
  reg [7:0] io_output_4_REG;
  reg [7:0] io_output_5_REG;
  reg [7:0] io_output_6_REG;
  reg [7:0] io_output_7_REG;
  reg [7:0] io_output_8_REG;
  reg [7:0] io_output_9_REG;
  reg [7:0] io_output_10_REG;
  reg [7:0] io_output_11_REG;
  reg [7:0] io_output_12_REG;
  reg [7:0] io_output_13_REG;
  reg [7:0] io_output_14_REG;
  reg [7:0] io_output_15_REG;
  reg [7:0] io_output_16_REG;
  reg [7:0] io_output_17_REG;
  reg [7:0] io_output_18_REG;
  reg [7:0] io_output_19_REG;
  reg [7:0] io_output_20_REG;
  reg [7:0] io_output_21_REG;
  reg [7:0] io_output_22_REG;
  reg [7:0] io_output_23_REG;
  reg [7:0] io_output_24_REG;
  reg [7:0] io_output_25_REG;
  reg [7:0] io_output_26_REG;
  reg [7:0] io_output_27_REG;
  reg [7:0] io_output_28_REG;
  reg [7:0] io_output_29_REG;
  reg [7:0] io_output_30_REG;
  reg [7:0] io_output_31_REG;
  always @(posedge clock) begin
    if (reset) begin
      io_output_0_REG <= 8'h0;
      io_output_1_REG <= 8'h0;
      io_output_2_REG <= 8'h0;
      io_output_3_REG <= 8'h0;
      io_output_4_REG <= 8'h0;
      io_output_5_REG <= 8'h0;
      io_output_6_REG <= 8'h0;
      io_output_7_REG <= 8'h0;
      io_output_8_REG <= 8'h0;
      io_output_9_REG <= 8'h0;
      io_output_10_REG <= 8'h0;
      io_output_11_REG <= 8'h0;
      io_output_12_REG <= 8'h0;
      io_output_13_REG <= 8'h0;
      io_output_14_REG <= 8'h0;
      io_output_15_REG <= 8'h0;
      io_output_16_REG <= 8'h0;
      io_output_17_REG <= 8'h0;
      io_output_18_REG <= 8'h0;
      io_output_19_REG <= 8'h0;
      io_output_20_REG <= 8'h0;
      io_output_21_REG <= 8'h0;
      io_output_22_REG <= 8'h0;
      io_output_23_REG <= 8'h0;
      io_output_24_REG <= 8'h0;
      io_output_25_REG <= 8'h0;
      io_output_26_REG <= 8'h0;
      io_output_27_REG <= 8'h0;
      io_output_28_REG <= 8'h0;
      io_output_29_REG <= 8'h0;
      io_output_30_REG <= 8'h0;
      io_output_31_REG <= 8'h0;
    end
    else begin
      io_output_0_REG <= io_input_0;
      io_output_1_REG <= io_input_1;
      io_output_2_REG <= io_input_2;
      io_output_3_REG <= io_input_3;
      io_output_4_REG <= io_input_4;
      io_output_5_REG <= io_input_5;
      io_output_6_REG <= io_input_6;
      io_output_7_REG <= io_input_7;
      io_output_8_REG <= io_input_8;
      io_output_9_REG <= io_input_9;
      io_output_10_REG <= io_input_10;
      io_output_11_REG <= io_input_11;
      io_output_12_REG <= io_input_12;
      io_output_13_REG <= io_input_13;
      io_output_14_REG <= io_input_14;
      io_output_15_REG <= io_input_15;
      io_output_16_REG <= io_input_16;
      io_output_17_REG <= io_input_17;
      io_output_18_REG <= io_input_18;
      io_output_19_REG <= io_input_19;
      io_output_20_REG <= io_input_20;
      io_output_21_REG <= io_input_21;
      io_output_22_REG <= io_input_22;
      io_output_23_REG <= io_input_23;
      io_output_24_REG <= io_input_24;
      io_output_25_REG <= io_input_25;
      io_output_26_REG <= io_input_26;
      io_output_27_REG <= io_input_27;
      io_output_28_REG <= io_input_28;
      io_output_29_REG <= io_input_29;
      io_output_30_REG <= io_input_30;
      io_output_31_REG <= io_input_31;
    end
  end // always @(posedge)
  assign io_output_0 = io_output_0_REG;
  assign io_output_1 = io_output_1_REG;
  assign io_output_2 = io_output_2_REG;
  assign io_output_3 = io_output_3_REG;
  assign io_output_4 = io_output_4_REG;
  assign io_output_5 = io_output_5_REG;
  assign io_output_6 = io_output_6_REG;
  assign io_output_7 = io_output_7_REG;
  assign io_output_8 = io_output_8_REG;
  assign io_output_9 = io_output_9_REG;
  assign io_output_10 = io_output_10_REG;
  assign io_output_11 = io_output_11_REG;
  assign io_output_12 = io_output_12_REG;
  assign io_output_13 = io_output_13_REG;
  assign io_output_14 = io_output_14_REG;
  assign io_output_15 = io_output_15_REG;
  assign io_output_16 = io_output_16_REG;
  assign io_output_17 = io_output_17_REG;
  assign io_output_18 = io_output_18_REG;
  assign io_output_19 = io_output_19_REG;
  assign io_output_20 = io_output_20_REG;
  assign io_output_21 = io_output_21_REG;
  assign io_output_22 = io_output_22_REG;
  assign io_output_23 = io_output_23_REG;
  assign io_output_24 = io_output_24_REG;
  assign io_output_25 = io_output_25_REG;
  assign io_output_26 = io_output_26_REG;
  assign io_output_27 = io_output_27_REG;
  assign io_output_28 = io_output_28_REG;
  assign io_output_29 = io_output_29_REG;
  assign io_output_30 = io_output_30_REG;
  assign io_output_31 = io_output_31_REG;
endmodule

