// Generated by CIRCT firtool-1.62.0
module ws_sta_32x32x1x1x1(
  input         clock,
                reset,
  input  [7:0]  io_inputA_0,
                io_inputA_1,
                io_inputA_2,
                io_inputA_3,
                io_inputA_4,
                io_inputA_5,
                io_inputA_6,
                io_inputA_7,
                io_inputA_8,
                io_inputA_9,
                io_inputA_10,
                io_inputA_11,
                io_inputA_12,
                io_inputA_13,
                io_inputA_14,
                io_inputA_15,
                io_inputA_16,
                io_inputA_17,
                io_inputA_18,
                io_inputA_19,
                io_inputA_20,
                io_inputA_21,
                io_inputA_22,
                io_inputA_23,
                io_inputA_24,
                io_inputA_25,
                io_inputA_26,
                io_inputA_27,
                io_inputA_28,
                io_inputA_29,
                io_inputA_30,
                io_inputA_31,
                io_inputB_0,
                io_inputB_1,
                io_inputB_2,
                io_inputB_3,
                io_inputB_4,
                io_inputB_5,
                io_inputB_6,
                io_inputB_7,
                io_inputB_8,
                io_inputB_9,
                io_inputB_10,
                io_inputB_11,
                io_inputB_12,
                io_inputB_13,
                io_inputB_14,
                io_inputB_15,
                io_inputB_16,
                io_inputB_17,
                io_inputB_18,
                io_inputB_19,
                io_inputB_20,
                io_inputB_21,
                io_inputB_22,
                io_inputB_23,
                io_inputB_24,
                io_inputB_25,
                io_inputB_26,
                io_inputB_27,
                io_inputB_28,
                io_inputB_29,
                io_inputB_30,
                io_inputB_31,
  input         io_propagateB_0,
                io_propagateB_1,
                io_propagateB_2,
                io_propagateB_3,
                io_propagateB_4,
                io_propagateB_5,
                io_propagateB_6,
                io_propagateB_7,
                io_propagateB_8,
                io_propagateB_9,
                io_propagateB_10,
                io_propagateB_11,
                io_propagateB_12,
                io_propagateB_13,
                io_propagateB_14,
                io_propagateB_15,
                io_propagateB_16,
                io_propagateB_17,
                io_propagateB_18,
                io_propagateB_19,
                io_propagateB_20,
                io_propagateB_21,
                io_propagateB_22,
                io_propagateB_23,
                io_propagateB_24,
                io_propagateB_25,
                io_propagateB_26,
                io_propagateB_27,
                io_propagateB_28,
                io_propagateB_29,
                io_propagateB_30,
                io_propagateB_31,
  output [20:0] io_outputC_0,
                io_outputC_1,
                io_outputC_2,
                io_outputC_3,
                io_outputC_4,
                io_outputC_5,
                io_outputC_6,
                io_outputC_7,
                io_outputC_8,
                io_outputC_9,
                io_outputC_10,
                io_outputC_11,
                io_outputC_12,
                io_outputC_13,
                io_outputC_14,
                io_outputC_15,
                io_outputC_16,
                io_outputC_17,
                io_outputC_18,
                io_outputC_19,
                io_outputC_20,
                io_outputC_21,
                io_outputC_22,
                io_outputC_23,
                io_outputC_24,
                io_outputC_25,
                io_outputC_26,
                io_outputC_27,
                io_outputC_28,
                io_outputC_29,
                io_outputC_30,
                io_outputC_31
);

  wire [20:0] _systolicTensorArray_io_outputC_0;
  wire [20:0] _systolicTensorArray_io_outputC_1;
  wire [20:0] _systolicTensorArray_io_outputC_2;
  wire [20:0] _systolicTensorArray_io_outputC_3;
  wire [20:0] _systolicTensorArray_io_outputC_4;
  wire [20:0] _systolicTensorArray_io_outputC_5;
  wire [20:0] _systolicTensorArray_io_outputC_6;
  wire [20:0] _systolicTensorArray_io_outputC_7;
  wire [20:0] _systolicTensorArray_io_outputC_8;
  wire [20:0] _systolicTensorArray_io_outputC_9;
  wire [20:0] _systolicTensorArray_io_outputC_10;
  wire [20:0] _systolicTensorArray_io_outputC_11;
  wire [20:0] _systolicTensorArray_io_outputC_12;
  wire [20:0] _systolicTensorArray_io_outputC_13;
  wire [20:0] _systolicTensorArray_io_outputC_14;
  wire [20:0] _systolicTensorArray_io_outputC_15;
  wire [20:0] _systolicTensorArray_io_outputC_16;
  wire [20:0] _systolicTensorArray_io_outputC_17;
  wire [20:0] _systolicTensorArray_io_outputC_18;
  wire [20:0] _systolicTensorArray_io_outputC_19;
  wire [20:0] _systolicTensorArray_io_outputC_20;
  wire [20:0] _systolicTensorArray_io_outputC_21;
  wire [20:0] _systolicTensorArray_io_outputC_22;
  wire [20:0] _systolicTensorArray_io_outputC_23;
  wire [20:0] _systolicTensorArray_io_outputC_24;
  wire [20:0] _systolicTensorArray_io_outputC_25;
  wire [20:0] _systolicTensorArray_io_outputC_26;
  wire [20:0] _systolicTensorArray_io_outputC_27;
  wire [20:0] _systolicTensorArray_io_outputC_28;
  wire [20:0] _systolicTensorArray_io_outputC_29;
  wire [20:0] _systolicTensorArray_io_outputC_30;
  wire [20:0] _systolicTensorArray_io_outputC_31;
  wire [7:0]  _preProcessorInputB_io_output_0;
  wire [7:0]  _preProcessorInputB_io_output_1;
  wire [7:0]  _preProcessorInputB_io_output_2;
  wire [7:0]  _preProcessorInputB_io_output_3;
  wire [7:0]  _preProcessorInputB_io_output_4;
  wire [7:0]  _preProcessorInputB_io_output_5;
  wire [7:0]  _preProcessorInputB_io_output_6;
  wire [7:0]  _preProcessorInputB_io_output_7;
  wire [7:0]  _preProcessorInputB_io_output_8;
  wire [7:0]  _preProcessorInputB_io_output_9;
  wire [7:0]  _preProcessorInputB_io_output_10;
  wire [7:0]  _preProcessorInputB_io_output_11;
  wire [7:0]  _preProcessorInputB_io_output_12;
  wire [7:0]  _preProcessorInputB_io_output_13;
  wire [7:0]  _preProcessorInputB_io_output_14;
  wire [7:0]  _preProcessorInputB_io_output_15;
  wire [7:0]  _preProcessorInputB_io_output_16;
  wire [7:0]  _preProcessorInputB_io_output_17;
  wire [7:0]  _preProcessorInputB_io_output_18;
  wire [7:0]  _preProcessorInputB_io_output_19;
  wire [7:0]  _preProcessorInputB_io_output_20;
  wire [7:0]  _preProcessorInputB_io_output_21;
  wire [7:0]  _preProcessorInputB_io_output_22;
  wire [7:0]  _preProcessorInputB_io_output_23;
  wire [7:0]  _preProcessorInputB_io_output_24;
  wire [7:0]  _preProcessorInputB_io_output_25;
  wire [7:0]  _preProcessorInputB_io_output_26;
  wire [7:0]  _preProcessorInputB_io_output_27;
  wire [7:0]  _preProcessorInputB_io_output_28;
  wire [7:0]  _preProcessorInputB_io_output_29;
  wire [7:0]  _preProcessorInputB_io_output_30;
  wire [7:0]  _preProcessorInputB_io_output_31;
  wire [7:0]  _preProcessorInputA_io_output_0;
  wire [7:0]  _preProcessorInputA_io_output_1;
  wire [7:0]  _preProcessorInputA_io_output_2;
  wire [7:0]  _preProcessorInputA_io_output_3;
  wire [7:0]  _preProcessorInputA_io_output_4;
  wire [7:0]  _preProcessorInputA_io_output_5;
  wire [7:0]  _preProcessorInputA_io_output_6;
  wire [7:0]  _preProcessorInputA_io_output_7;
  wire [7:0]  _preProcessorInputA_io_output_8;
  wire [7:0]  _preProcessorInputA_io_output_9;
  wire [7:0]  _preProcessorInputA_io_output_10;
  wire [7:0]  _preProcessorInputA_io_output_11;
  wire [7:0]  _preProcessorInputA_io_output_12;
  wire [7:0]  _preProcessorInputA_io_output_13;
  wire [7:0]  _preProcessorInputA_io_output_14;
  wire [7:0]  _preProcessorInputA_io_output_15;
  wire [7:0]  _preProcessorInputA_io_output_16;
  wire [7:0]  _preProcessorInputA_io_output_17;
  wire [7:0]  _preProcessorInputA_io_output_18;
  wire [7:0]  _preProcessorInputA_io_output_19;
  wire [7:0]  _preProcessorInputA_io_output_20;
  wire [7:0]  _preProcessorInputA_io_output_21;
  wire [7:0]  _preProcessorInputA_io_output_22;
  wire [7:0]  _preProcessorInputA_io_output_23;
  wire [7:0]  _preProcessorInputA_io_output_24;
  wire [7:0]  _preProcessorInputA_io_output_25;
  wire [7:0]  _preProcessorInputA_io_output_26;
  wire [7:0]  _preProcessorInputA_io_output_27;
  wire [7:0]  _preProcessorInputA_io_output_28;
  wire [7:0]  _preProcessorInputA_io_output_29;
  wire [7:0]  _preProcessorInputA_io_output_30;
  wire [7:0]  _preProcessorInputA_io_output_31;
  reg         REG_0;
  reg         REG_1;
  reg         REG_2;
  reg         REG_3;
  reg         REG_4;
  reg         REG_5;
  reg         REG_6;
  reg         REG_7;
  reg         REG_8;
  reg         REG_9;
  reg         REG_10;
  reg         REG_11;
  reg         REG_12;
  reg         REG_13;
  reg         REG_14;
  reg         REG_15;
  reg         REG_16;
  reg         REG_17;
  reg         REG_18;
  reg         REG_19;
  reg         REG_20;
  reg         REG_21;
  reg         REG_22;
  reg         REG_23;
  reg         REG_24;
  reg         REG_25;
  reg         REG_26;
  reg         REG_27;
  reg         REG_28;
  reg         REG_29;
  reg         REG_30;
  reg         REG_31;
  always @(posedge clock) begin
    if (reset) begin
      REG_0 <= 1'h0;
      REG_1 <= 1'h0;
      REG_2 <= 1'h0;
      REG_3 <= 1'h0;
      REG_4 <= 1'h0;
      REG_5 <= 1'h0;
      REG_6 <= 1'h0;
      REG_7 <= 1'h0;
      REG_8 <= 1'h0;
      REG_9 <= 1'h0;
      REG_10 <= 1'h0;
      REG_11 <= 1'h0;
      REG_12 <= 1'h0;
      REG_13 <= 1'h0;
      REG_14 <= 1'h0;
      REG_15 <= 1'h0;
      REG_16 <= 1'h0;
      REG_17 <= 1'h0;
      REG_18 <= 1'h0;
      REG_19 <= 1'h0;
      REG_20 <= 1'h0;
      REG_21 <= 1'h0;
      REG_22 <= 1'h0;
      REG_23 <= 1'h0;
      REG_24 <= 1'h0;
      REG_25 <= 1'h0;
      REG_26 <= 1'h0;
      REG_27 <= 1'h0;
      REG_28 <= 1'h0;
      REG_29 <= 1'h0;
      REG_30 <= 1'h0;
      REG_31 <= 1'h0;
    end
    else begin
      REG_0 <= io_propagateB_0;
      REG_1 <= io_propagateB_1;
      REG_2 <= io_propagateB_2;
      REG_3 <= io_propagateB_3;
      REG_4 <= io_propagateB_4;
      REG_5 <= io_propagateB_5;
      REG_6 <= io_propagateB_6;
      REG_7 <= io_propagateB_7;
      REG_8 <= io_propagateB_8;
      REG_9 <= io_propagateB_9;
      REG_10 <= io_propagateB_10;
      REG_11 <= io_propagateB_11;
      REG_12 <= io_propagateB_12;
      REG_13 <= io_propagateB_13;
      REG_14 <= io_propagateB_14;
      REG_15 <= io_propagateB_15;
      REG_16 <= io_propagateB_16;
      REG_17 <= io_propagateB_17;
      REG_18 <= io_propagateB_18;
      REG_19 <= io_propagateB_19;
      REG_20 <= io_propagateB_20;
      REG_21 <= io_propagateB_21;
      REG_22 <= io_propagateB_22;
      REG_23 <= io_propagateB_23;
      REG_24 <= io_propagateB_24;
      REG_25 <= io_propagateB_25;
      REG_26 <= io_propagateB_26;
      REG_27 <= io_propagateB_27;
      REG_28 <= io_propagateB_28;
      REG_29 <= io_propagateB_29;
      REG_30 <= io_propagateB_30;
      REG_31 <= io_propagateB_31;
    end
  end // always @(posedge)
  pre_processor_a preProcessorInputA (
    .clock        (clock),
    .reset        (reset),
    .io_input_0   (io_inputA_0),
    .io_input_1   (io_inputA_1),
    .io_input_2   (io_inputA_2),
    .io_input_3   (io_inputA_3),
    .io_input_4   (io_inputA_4),
    .io_input_5   (io_inputA_5),
    .io_input_6   (io_inputA_6),
    .io_input_7   (io_inputA_7),
    .io_input_8   (io_inputA_8),
    .io_input_9   (io_inputA_9),
    .io_input_10  (io_inputA_10),
    .io_input_11  (io_inputA_11),
    .io_input_12  (io_inputA_12),
    .io_input_13  (io_inputA_13),
    .io_input_14  (io_inputA_14),
    .io_input_15  (io_inputA_15),
    .io_input_16  (io_inputA_16),
    .io_input_17  (io_inputA_17),
    .io_input_18  (io_inputA_18),
    .io_input_19  (io_inputA_19),
    .io_input_20  (io_inputA_20),
    .io_input_21  (io_inputA_21),
    .io_input_22  (io_inputA_22),
    .io_input_23  (io_inputA_23),
    .io_input_24  (io_inputA_24),
    .io_input_25  (io_inputA_25),
    .io_input_26  (io_inputA_26),
    .io_input_27  (io_inputA_27),
    .io_input_28  (io_inputA_28),
    .io_input_29  (io_inputA_29),
    .io_input_30  (io_inputA_30),
    .io_input_31  (io_inputA_31),
    .io_output_0  (_preProcessorInputA_io_output_0),
    .io_output_1  (_preProcessorInputA_io_output_1),
    .io_output_2  (_preProcessorInputA_io_output_2),
    .io_output_3  (_preProcessorInputA_io_output_3),
    .io_output_4  (_preProcessorInputA_io_output_4),
    .io_output_5  (_preProcessorInputA_io_output_5),
    .io_output_6  (_preProcessorInputA_io_output_6),
    .io_output_7  (_preProcessorInputA_io_output_7),
    .io_output_8  (_preProcessorInputA_io_output_8),
    .io_output_9  (_preProcessorInputA_io_output_9),
    .io_output_10 (_preProcessorInputA_io_output_10),
    .io_output_11 (_preProcessorInputA_io_output_11),
    .io_output_12 (_preProcessorInputA_io_output_12),
    .io_output_13 (_preProcessorInputA_io_output_13),
    .io_output_14 (_preProcessorInputA_io_output_14),
    .io_output_15 (_preProcessorInputA_io_output_15),
    .io_output_16 (_preProcessorInputA_io_output_16),
    .io_output_17 (_preProcessorInputA_io_output_17),
    .io_output_18 (_preProcessorInputA_io_output_18),
    .io_output_19 (_preProcessorInputA_io_output_19),
    .io_output_20 (_preProcessorInputA_io_output_20),
    .io_output_21 (_preProcessorInputA_io_output_21),
    .io_output_22 (_preProcessorInputA_io_output_22),
    .io_output_23 (_preProcessorInputA_io_output_23),
    .io_output_24 (_preProcessorInputA_io_output_24),
    .io_output_25 (_preProcessorInputA_io_output_25),
    .io_output_26 (_preProcessorInputA_io_output_26),
    .io_output_27 (_preProcessorInputA_io_output_27),
    .io_output_28 (_preProcessorInputA_io_output_28),
    .io_output_29 (_preProcessorInputA_io_output_29),
    .io_output_30 (_preProcessorInputA_io_output_30),
    .io_output_31 (_preProcessorInputA_io_output_31)
  );
  pre_processor_b preProcessorInputB (
    .clock        (clock),
    .reset        (reset),
    .io_input_0   (io_inputB_0),
    .io_input_1   (io_inputB_1),
    .io_input_2   (io_inputB_2),
    .io_input_3   (io_inputB_3),
    .io_input_4   (io_inputB_4),
    .io_input_5   (io_inputB_5),
    .io_input_6   (io_inputB_6),
    .io_input_7   (io_inputB_7),
    .io_input_8   (io_inputB_8),
    .io_input_9   (io_inputB_9),
    .io_input_10  (io_inputB_10),
    .io_input_11  (io_inputB_11),
    .io_input_12  (io_inputB_12),
    .io_input_13  (io_inputB_13),
    .io_input_14  (io_inputB_14),
    .io_input_15  (io_inputB_15),
    .io_input_16  (io_inputB_16),
    .io_input_17  (io_inputB_17),
    .io_input_18  (io_inputB_18),
    .io_input_19  (io_inputB_19),
    .io_input_20  (io_inputB_20),
    .io_input_21  (io_inputB_21),
    .io_input_22  (io_inputB_22),
    .io_input_23  (io_inputB_23),
    .io_input_24  (io_inputB_24),
    .io_input_25  (io_inputB_25),
    .io_input_26  (io_inputB_26),
    .io_input_27  (io_inputB_27),
    .io_input_28  (io_inputB_28),
    .io_input_29  (io_inputB_29),
    .io_input_30  (io_inputB_30),
    .io_input_31  (io_inputB_31),
    .io_output_0  (_preProcessorInputB_io_output_0),
    .io_output_1  (_preProcessorInputB_io_output_1),
    .io_output_2  (_preProcessorInputB_io_output_2),
    .io_output_3  (_preProcessorInputB_io_output_3),
    .io_output_4  (_preProcessorInputB_io_output_4),
    .io_output_5  (_preProcessorInputB_io_output_5),
    .io_output_6  (_preProcessorInputB_io_output_6),
    .io_output_7  (_preProcessorInputB_io_output_7),
    .io_output_8  (_preProcessorInputB_io_output_8),
    .io_output_9  (_preProcessorInputB_io_output_9),
    .io_output_10 (_preProcessorInputB_io_output_10),
    .io_output_11 (_preProcessorInputB_io_output_11),
    .io_output_12 (_preProcessorInputB_io_output_12),
    .io_output_13 (_preProcessorInputB_io_output_13),
    .io_output_14 (_preProcessorInputB_io_output_14),
    .io_output_15 (_preProcessorInputB_io_output_15),
    .io_output_16 (_preProcessorInputB_io_output_16),
    .io_output_17 (_preProcessorInputB_io_output_17),
    .io_output_18 (_preProcessorInputB_io_output_18),
    .io_output_19 (_preProcessorInputB_io_output_19),
    .io_output_20 (_preProcessorInputB_io_output_20),
    .io_output_21 (_preProcessorInputB_io_output_21),
    .io_output_22 (_preProcessorInputB_io_output_22),
    .io_output_23 (_preProcessorInputB_io_output_23),
    .io_output_24 (_preProcessorInputB_io_output_24),
    .io_output_25 (_preProcessorInputB_io_output_25),
    .io_output_26 (_preProcessorInputB_io_output_26),
    .io_output_27 (_preProcessorInputB_io_output_27),
    .io_output_28 (_preProcessorInputB_io_output_28),
    .io_output_29 (_preProcessorInputB_io_output_29),
    .io_output_30 (_preProcessorInputB_io_output_30),
    .io_output_31 (_preProcessorInputB_io_output_31)
  );
  systolic_tensor_array systolicTensorArray (
    .clock            (clock),
    .reset            (reset),
    .io_inputA_0      (_preProcessorInputA_io_output_0),
    .io_inputA_1      (_preProcessorInputA_io_output_1),
    .io_inputA_2      (_preProcessorInputA_io_output_2),
    .io_inputA_3      (_preProcessorInputA_io_output_3),
    .io_inputA_4      (_preProcessorInputA_io_output_4),
    .io_inputA_5      (_preProcessorInputA_io_output_5),
    .io_inputA_6      (_preProcessorInputA_io_output_6),
    .io_inputA_7      (_preProcessorInputA_io_output_7),
    .io_inputA_8      (_preProcessorInputA_io_output_8),
    .io_inputA_9      (_preProcessorInputA_io_output_9),
    .io_inputA_10     (_preProcessorInputA_io_output_10),
    .io_inputA_11     (_preProcessorInputA_io_output_11),
    .io_inputA_12     (_preProcessorInputA_io_output_12),
    .io_inputA_13     (_preProcessorInputA_io_output_13),
    .io_inputA_14     (_preProcessorInputA_io_output_14),
    .io_inputA_15     (_preProcessorInputA_io_output_15),
    .io_inputA_16     (_preProcessorInputA_io_output_16),
    .io_inputA_17     (_preProcessorInputA_io_output_17),
    .io_inputA_18     (_preProcessorInputA_io_output_18),
    .io_inputA_19     (_preProcessorInputA_io_output_19),
    .io_inputA_20     (_preProcessorInputA_io_output_20),
    .io_inputA_21     (_preProcessorInputA_io_output_21),
    .io_inputA_22     (_preProcessorInputA_io_output_22),
    .io_inputA_23     (_preProcessorInputA_io_output_23),
    .io_inputA_24     (_preProcessorInputA_io_output_24),
    .io_inputA_25     (_preProcessorInputA_io_output_25),
    .io_inputA_26     (_preProcessorInputA_io_output_26),
    .io_inputA_27     (_preProcessorInputA_io_output_27),
    .io_inputA_28     (_preProcessorInputA_io_output_28),
    .io_inputA_29     (_preProcessorInputA_io_output_29),
    .io_inputA_30     (_preProcessorInputA_io_output_30),
    .io_inputA_31     (_preProcessorInputA_io_output_31),
    .io_inputB_0      (_preProcessorInputB_io_output_0),
    .io_inputB_1      (_preProcessorInputB_io_output_1),
    .io_inputB_2      (_preProcessorInputB_io_output_2),
    .io_inputB_3      (_preProcessorInputB_io_output_3),
    .io_inputB_4      (_preProcessorInputB_io_output_4),
    .io_inputB_5      (_preProcessorInputB_io_output_5),
    .io_inputB_6      (_preProcessorInputB_io_output_6),
    .io_inputB_7      (_preProcessorInputB_io_output_7),
    .io_inputB_8      (_preProcessorInputB_io_output_8),
    .io_inputB_9      (_preProcessorInputB_io_output_9),
    .io_inputB_10     (_preProcessorInputB_io_output_10),
    .io_inputB_11     (_preProcessorInputB_io_output_11),
    .io_inputB_12     (_preProcessorInputB_io_output_12),
    .io_inputB_13     (_preProcessorInputB_io_output_13),
    .io_inputB_14     (_preProcessorInputB_io_output_14),
    .io_inputB_15     (_preProcessorInputB_io_output_15),
    .io_inputB_16     (_preProcessorInputB_io_output_16),
    .io_inputB_17     (_preProcessorInputB_io_output_17),
    .io_inputB_18     (_preProcessorInputB_io_output_18),
    .io_inputB_19     (_preProcessorInputB_io_output_19),
    .io_inputB_20     (_preProcessorInputB_io_output_20),
    .io_inputB_21     (_preProcessorInputB_io_output_21),
    .io_inputB_22     (_preProcessorInputB_io_output_22),
    .io_inputB_23     (_preProcessorInputB_io_output_23),
    .io_inputB_24     (_preProcessorInputB_io_output_24),
    .io_inputB_25     (_preProcessorInputB_io_output_25),
    .io_inputB_26     (_preProcessorInputB_io_output_26),
    .io_inputB_27     (_preProcessorInputB_io_output_27),
    .io_inputB_28     (_preProcessorInputB_io_output_28),
    .io_inputB_29     (_preProcessorInputB_io_output_29),
    .io_inputB_30     (_preProcessorInputB_io_output_30),
    .io_inputB_31     (_preProcessorInputB_io_output_31),
    .io_propagateB_0  (REG_0),
    .io_propagateB_1  (REG_1),
    .io_propagateB_2  (REG_2),
    .io_propagateB_3  (REG_3),
    .io_propagateB_4  (REG_4),
    .io_propagateB_5  (REG_5),
    .io_propagateB_6  (REG_6),
    .io_propagateB_7  (REG_7),
    .io_propagateB_8  (REG_8),
    .io_propagateB_9  (REG_9),
    .io_propagateB_10 (REG_10),
    .io_propagateB_11 (REG_11),
    .io_propagateB_12 (REG_12),
    .io_propagateB_13 (REG_13),
    .io_propagateB_14 (REG_14),
    .io_propagateB_15 (REG_15),
    .io_propagateB_16 (REG_16),
    .io_propagateB_17 (REG_17),
    .io_propagateB_18 (REG_18),
    .io_propagateB_19 (REG_19),
    .io_propagateB_20 (REG_20),
    .io_propagateB_21 (REG_21),
    .io_propagateB_22 (REG_22),
    .io_propagateB_23 (REG_23),
    .io_propagateB_24 (REG_24),
    .io_propagateB_25 (REG_25),
    .io_propagateB_26 (REG_26),
    .io_propagateB_27 (REG_27),
    .io_propagateB_28 (REG_28),
    .io_propagateB_29 (REG_29),
    .io_propagateB_30 (REG_30),
    .io_propagateB_31 (REG_31),
    .io_outputC_0     (_systolicTensorArray_io_outputC_0),
    .io_outputC_1     (_systolicTensorArray_io_outputC_1),
    .io_outputC_2     (_systolicTensorArray_io_outputC_2),
    .io_outputC_3     (_systolicTensorArray_io_outputC_3),
    .io_outputC_4     (_systolicTensorArray_io_outputC_4),
    .io_outputC_5     (_systolicTensorArray_io_outputC_5),
    .io_outputC_6     (_systolicTensorArray_io_outputC_6),
    .io_outputC_7     (_systolicTensorArray_io_outputC_7),
    .io_outputC_8     (_systolicTensorArray_io_outputC_8),
    .io_outputC_9     (_systolicTensorArray_io_outputC_9),
    .io_outputC_10    (_systolicTensorArray_io_outputC_10),
    .io_outputC_11    (_systolicTensorArray_io_outputC_11),
    .io_outputC_12    (_systolicTensorArray_io_outputC_12),
    .io_outputC_13    (_systolicTensorArray_io_outputC_13),
    .io_outputC_14    (_systolicTensorArray_io_outputC_14),
    .io_outputC_15    (_systolicTensorArray_io_outputC_15),
    .io_outputC_16    (_systolicTensorArray_io_outputC_16),
    .io_outputC_17    (_systolicTensorArray_io_outputC_17),
    .io_outputC_18    (_systolicTensorArray_io_outputC_18),
    .io_outputC_19    (_systolicTensorArray_io_outputC_19),
    .io_outputC_20    (_systolicTensorArray_io_outputC_20),
    .io_outputC_21    (_systolicTensorArray_io_outputC_21),
    .io_outputC_22    (_systolicTensorArray_io_outputC_22),
    .io_outputC_23    (_systolicTensorArray_io_outputC_23),
    .io_outputC_24    (_systolicTensorArray_io_outputC_24),
    .io_outputC_25    (_systolicTensorArray_io_outputC_25),
    .io_outputC_26    (_systolicTensorArray_io_outputC_26),
    .io_outputC_27    (_systolicTensorArray_io_outputC_27),
    .io_outputC_28    (_systolicTensorArray_io_outputC_28),
    .io_outputC_29    (_systolicTensorArray_io_outputC_29),
    .io_outputC_30    (_systolicTensorArray_io_outputC_30),
    .io_outputC_31    (_systolicTensorArray_io_outputC_31)
  );
  post_processor postProcessor (
    .clock        (clock),
    .reset        (reset),
    .io_input_0   (_systolicTensorArray_io_outputC_0),
    .io_input_1   (_systolicTensorArray_io_outputC_1),
    .io_input_2   (_systolicTensorArray_io_outputC_2),
    .io_input_3   (_systolicTensorArray_io_outputC_3),
    .io_input_4   (_systolicTensorArray_io_outputC_4),
    .io_input_5   (_systolicTensorArray_io_outputC_5),
    .io_input_6   (_systolicTensorArray_io_outputC_6),
    .io_input_7   (_systolicTensorArray_io_outputC_7),
    .io_input_8   (_systolicTensorArray_io_outputC_8),
    .io_input_9   (_systolicTensorArray_io_outputC_9),
    .io_input_10  (_systolicTensorArray_io_outputC_10),
    .io_input_11  (_systolicTensorArray_io_outputC_11),
    .io_input_12  (_systolicTensorArray_io_outputC_12),
    .io_input_13  (_systolicTensorArray_io_outputC_13),
    .io_input_14  (_systolicTensorArray_io_outputC_14),
    .io_input_15  (_systolicTensorArray_io_outputC_15),
    .io_input_16  (_systolicTensorArray_io_outputC_16),
    .io_input_17  (_systolicTensorArray_io_outputC_17),
    .io_input_18  (_systolicTensorArray_io_outputC_18),
    .io_input_19  (_systolicTensorArray_io_outputC_19),
    .io_input_20  (_systolicTensorArray_io_outputC_20),
    .io_input_21  (_systolicTensorArray_io_outputC_21),
    .io_input_22  (_systolicTensorArray_io_outputC_22),
    .io_input_23  (_systolicTensorArray_io_outputC_23),
    .io_input_24  (_systolicTensorArray_io_outputC_24),
    .io_input_25  (_systolicTensorArray_io_outputC_25),
    .io_input_26  (_systolicTensorArray_io_outputC_26),
    .io_input_27  (_systolicTensorArray_io_outputC_27),
    .io_input_28  (_systolicTensorArray_io_outputC_28),
    .io_input_29  (_systolicTensorArray_io_outputC_29),
    .io_input_30  (_systolicTensorArray_io_outputC_30),
    .io_input_31  (_systolicTensorArray_io_outputC_31),
    .io_output_0  (io_outputC_0),
    .io_output_1  (io_outputC_1),
    .io_output_2  (io_outputC_2),
    .io_output_3  (io_outputC_3),
    .io_output_4  (io_outputC_4),
    .io_output_5  (io_outputC_5),
    .io_output_6  (io_outputC_6),
    .io_output_7  (io_outputC_7),
    .io_output_8  (io_outputC_8),
    .io_output_9  (io_outputC_9),
    .io_output_10 (io_outputC_10),
    .io_output_11 (io_outputC_11),
    .io_output_12 (io_outputC_12),
    .io_output_13 (io_outputC_13),
    .io_output_14 (io_outputC_14),
    .io_output_15 (io_outputC_15),
    .io_output_16 (io_outputC_16),
    .io_output_17 (io_outputC_17),
    .io_output_18 (io_outputC_18),
    .io_output_19 (io_outputC_19),
    .io_output_20 (io_outputC_20),
    .io_output_21 (io_outputC_21),
    .io_output_22 (io_outputC_22),
    .io_output_23 (io_outputC_23),
    .io_output_24 (io_outputC_24),
    .io_output_25 (io_outputC_25),
    .io_output_26 (io_outputC_26),
    .io_output_27 (io_outputC_27),
    .io_output_28 (io_outputC_28),
    .io_output_29 (io_outputC_29),
    .io_output_30 (io_outputC_30),
    .io_output_31 (io_outputC_31)
  );
endmodule

