// Generated by CIRCT firtool-1.62.0
module pre_processor_b(
  input        clock,
               reset,
  input  [7:0] io_input_0,
               io_input_1,
               io_input_2,
               io_input_3,
               io_input_4,
               io_input_5,
               io_input_6,
               io_input_7,
               io_input_8,
               io_input_9,
               io_input_10,
               io_input_11,
               io_input_12,
               io_input_13,
               io_input_14,
               io_input_15,
               io_input_16,
               io_input_17,
               io_input_18,
               io_input_19,
               io_input_20,
               io_input_21,
               io_input_22,
               io_input_23,
               io_input_24,
               io_input_25,
               io_input_26,
               io_input_27,
               io_input_28,
               io_input_29,
               io_input_30,
               io_input_31,
               io_input_32,
               io_input_33,
               io_input_34,
               io_input_35,
               io_input_36,
               io_input_37,
               io_input_38,
               io_input_39,
               io_input_40,
               io_input_41,
               io_input_42,
               io_input_43,
               io_input_44,
               io_input_45,
               io_input_46,
               io_input_47,
               io_input_48,
               io_input_49,
               io_input_50,
               io_input_51,
               io_input_52,
               io_input_53,
               io_input_54,
               io_input_55,
               io_input_56,
               io_input_57,
               io_input_58,
               io_input_59,
               io_input_60,
               io_input_61,
               io_input_62,
               io_input_63,
  output [7:0] io_output_0,
               io_output_1,
               io_output_2,
               io_output_3,
               io_output_4,
               io_output_5,
               io_output_6,
               io_output_7,
               io_output_8,
               io_output_9,
               io_output_10,
               io_output_11,
               io_output_12,
               io_output_13,
               io_output_14,
               io_output_15,
               io_output_16,
               io_output_17,
               io_output_18,
               io_output_19,
               io_output_20,
               io_output_21,
               io_output_22,
               io_output_23,
               io_output_24,
               io_output_25,
               io_output_26,
               io_output_27,
               io_output_28,
               io_output_29,
               io_output_30,
               io_output_31,
               io_output_32,
               io_output_33,
               io_output_34,
               io_output_35,
               io_output_36,
               io_output_37,
               io_output_38,
               io_output_39,
               io_output_40,
               io_output_41,
               io_output_42,
               io_output_43,
               io_output_44,
               io_output_45,
               io_output_46,
               io_output_47,
               io_output_48,
               io_output_49,
               io_output_50,
               io_output_51,
               io_output_52,
               io_output_53,
               io_output_54,
               io_output_55,
               io_output_56,
               io_output_57,
               io_output_58,
               io_output_59,
               io_output_60,
               io_output_61,
               io_output_62,
               io_output_63
);

  reg [7:0] io_output_0_REG;
  reg [7:0] io_output_1_REG;
  reg [7:0] io_output_2_REG;
  reg [7:0] io_output_3_REG;
  reg [7:0] io_output_4_REG;
  reg [7:0] io_output_5_REG;
  reg [7:0] io_output_6_REG;
  reg [7:0] io_output_7_REG;
  reg [7:0] io_output_8_REG;
  reg [7:0] io_output_9_REG;
  reg [7:0] io_output_10_REG;
  reg [7:0] io_output_11_REG;
  reg [7:0] io_output_12_REG;
  reg [7:0] io_output_13_REG;
  reg [7:0] io_output_14_REG;
  reg [7:0] io_output_15_REG;
  reg [7:0] io_output_16_REG;
  reg [7:0] io_output_17_REG;
  reg [7:0] io_output_18_REG;
  reg [7:0] io_output_19_REG;
  reg [7:0] io_output_20_REG;
  reg [7:0] io_output_21_REG;
  reg [7:0] io_output_22_REG;
  reg [7:0] io_output_23_REG;
  reg [7:0] io_output_24_REG;
  reg [7:0] io_output_25_REG;
  reg [7:0] io_output_26_REG;
  reg [7:0] io_output_27_REG;
  reg [7:0] io_output_28_REG;
  reg [7:0] io_output_29_REG;
  reg [7:0] io_output_30_REG;
  reg [7:0] io_output_31_REG;
  reg [7:0] io_output_32_REG;
  reg [7:0] io_output_33_REG;
  reg [7:0] io_output_34_REG;
  reg [7:0] io_output_35_REG;
  reg [7:0] io_output_36_REG;
  reg [7:0] io_output_37_REG;
  reg [7:0] io_output_38_REG;
  reg [7:0] io_output_39_REG;
  reg [7:0] io_output_40_REG;
  reg [7:0] io_output_41_REG;
  reg [7:0] io_output_42_REG;
  reg [7:0] io_output_43_REG;
  reg [7:0] io_output_44_REG;
  reg [7:0] io_output_45_REG;
  reg [7:0] io_output_46_REG;
  reg [7:0] io_output_47_REG;
  reg [7:0] io_output_48_REG;
  reg [7:0] io_output_49_REG;
  reg [7:0] io_output_50_REG;
  reg [7:0] io_output_51_REG;
  reg [7:0] io_output_52_REG;
  reg [7:0] io_output_53_REG;
  reg [7:0] io_output_54_REG;
  reg [7:0] io_output_55_REG;
  reg [7:0] io_output_56_REG;
  reg [7:0] io_output_57_REG;
  reg [7:0] io_output_58_REG;
  reg [7:0] io_output_59_REG;
  reg [7:0] io_output_60_REG;
  reg [7:0] io_output_61_REG;
  reg [7:0] io_output_62_REG;
  reg [7:0] io_output_63_REG;
  always @(posedge clock) begin
    if (reset) begin
      io_output_0_REG <= 8'h0;
      io_output_1_REG <= 8'h0;
      io_output_2_REG <= 8'h0;
      io_output_3_REG <= 8'h0;
      io_output_4_REG <= 8'h0;
      io_output_5_REG <= 8'h0;
      io_output_6_REG <= 8'h0;
      io_output_7_REG <= 8'h0;
      io_output_8_REG <= 8'h0;
      io_output_9_REG <= 8'h0;
      io_output_10_REG <= 8'h0;
      io_output_11_REG <= 8'h0;
      io_output_12_REG <= 8'h0;
      io_output_13_REG <= 8'h0;
      io_output_14_REG <= 8'h0;
      io_output_15_REG <= 8'h0;
      io_output_16_REG <= 8'h0;
      io_output_17_REG <= 8'h0;
      io_output_18_REG <= 8'h0;
      io_output_19_REG <= 8'h0;
      io_output_20_REG <= 8'h0;
      io_output_21_REG <= 8'h0;
      io_output_22_REG <= 8'h0;
      io_output_23_REG <= 8'h0;
      io_output_24_REG <= 8'h0;
      io_output_25_REG <= 8'h0;
      io_output_26_REG <= 8'h0;
      io_output_27_REG <= 8'h0;
      io_output_28_REG <= 8'h0;
      io_output_29_REG <= 8'h0;
      io_output_30_REG <= 8'h0;
      io_output_31_REG <= 8'h0;
      io_output_32_REG <= 8'h0;
      io_output_33_REG <= 8'h0;
      io_output_34_REG <= 8'h0;
      io_output_35_REG <= 8'h0;
      io_output_36_REG <= 8'h0;
      io_output_37_REG <= 8'h0;
      io_output_38_REG <= 8'h0;
      io_output_39_REG <= 8'h0;
      io_output_40_REG <= 8'h0;
      io_output_41_REG <= 8'h0;
      io_output_42_REG <= 8'h0;
      io_output_43_REG <= 8'h0;
      io_output_44_REG <= 8'h0;
      io_output_45_REG <= 8'h0;
      io_output_46_REG <= 8'h0;
      io_output_47_REG <= 8'h0;
      io_output_48_REG <= 8'h0;
      io_output_49_REG <= 8'h0;
      io_output_50_REG <= 8'h0;
      io_output_51_REG <= 8'h0;
      io_output_52_REG <= 8'h0;
      io_output_53_REG <= 8'h0;
      io_output_54_REG <= 8'h0;
      io_output_55_REG <= 8'h0;
      io_output_56_REG <= 8'h0;
      io_output_57_REG <= 8'h0;
      io_output_58_REG <= 8'h0;
      io_output_59_REG <= 8'h0;
      io_output_60_REG <= 8'h0;
      io_output_61_REG <= 8'h0;
      io_output_62_REG <= 8'h0;
      io_output_63_REG <= 8'h0;
    end
    else begin
      io_output_0_REG <= io_input_0;
      io_output_1_REG <= io_input_1;
      io_output_2_REG <= io_input_2;
      io_output_3_REG <= io_input_3;
      io_output_4_REG <= io_input_4;
      io_output_5_REG <= io_input_5;
      io_output_6_REG <= io_input_6;
      io_output_7_REG <= io_input_7;
      io_output_8_REG <= io_input_8;
      io_output_9_REG <= io_input_9;
      io_output_10_REG <= io_input_10;
      io_output_11_REG <= io_input_11;
      io_output_12_REG <= io_input_12;
      io_output_13_REG <= io_input_13;
      io_output_14_REG <= io_input_14;
      io_output_15_REG <= io_input_15;
      io_output_16_REG <= io_input_16;
      io_output_17_REG <= io_input_17;
      io_output_18_REG <= io_input_18;
      io_output_19_REG <= io_input_19;
      io_output_20_REG <= io_input_20;
      io_output_21_REG <= io_input_21;
      io_output_22_REG <= io_input_22;
      io_output_23_REG <= io_input_23;
      io_output_24_REG <= io_input_24;
      io_output_25_REG <= io_input_25;
      io_output_26_REG <= io_input_26;
      io_output_27_REG <= io_input_27;
      io_output_28_REG <= io_input_28;
      io_output_29_REG <= io_input_29;
      io_output_30_REG <= io_input_30;
      io_output_31_REG <= io_input_31;
      io_output_32_REG <= io_input_32;
      io_output_33_REG <= io_input_33;
      io_output_34_REG <= io_input_34;
      io_output_35_REG <= io_input_35;
      io_output_36_REG <= io_input_36;
      io_output_37_REG <= io_input_37;
      io_output_38_REG <= io_input_38;
      io_output_39_REG <= io_input_39;
      io_output_40_REG <= io_input_40;
      io_output_41_REG <= io_input_41;
      io_output_42_REG <= io_input_42;
      io_output_43_REG <= io_input_43;
      io_output_44_REG <= io_input_44;
      io_output_45_REG <= io_input_45;
      io_output_46_REG <= io_input_46;
      io_output_47_REG <= io_input_47;
      io_output_48_REG <= io_input_48;
      io_output_49_REG <= io_input_49;
      io_output_50_REG <= io_input_50;
      io_output_51_REG <= io_input_51;
      io_output_52_REG <= io_input_52;
      io_output_53_REG <= io_input_53;
      io_output_54_REG <= io_input_54;
      io_output_55_REG <= io_input_55;
      io_output_56_REG <= io_input_56;
      io_output_57_REG <= io_input_57;
      io_output_58_REG <= io_input_58;
      io_output_59_REG <= io_input_59;
      io_output_60_REG <= io_input_60;
      io_output_61_REG <= io_input_61;
      io_output_62_REG <= io_input_62;
      io_output_63_REG <= io_input_63;
    end
  end // always @(posedge)
  assign io_output_0 = io_output_0_REG;
  assign io_output_1 = io_output_1_REG;
  assign io_output_2 = io_output_2_REG;
  assign io_output_3 = io_output_3_REG;
  assign io_output_4 = io_output_4_REG;
  assign io_output_5 = io_output_5_REG;
  assign io_output_6 = io_output_6_REG;
  assign io_output_7 = io_output_7_REG;
  assign io_output_8 = io_output_8_REG;
  assign io_output_9 = io_output_9_REG;
  assign io_output_10 = io_output_10_REG;
  assign io_output_11 = io_output_11_REG;
  assign io_output_12 = io_output_12_REG;
  assign io_output_13 = io_output_13_REG;
  assign io_output_14 = io_output_14_REG;
  assign io_output_15 = io_output_15_REG;
  assign io_output_16 = io_output_16_REG;
  assign io_output_17 = io_output_17_REG;
  assign io_output_18 = io_output_18_REG;
  assign io_output_19 = io_output_19_REG;
  assign io_output_20 = io_output_20_REG;
  assign io_output_21 = io_output_21_REG;
  assign io_output_22 = io_output_22_REG;
  assign io_output_23 = io_output_23_REG;
  assign io_output_24 = io_output_24_REG;
  assign io_output_25 = io_output_25_REG;
  assign io_output_26 = io_output_26_REG;
  assign io_output_27 = io_output_27_REG;
  assign io_output_28 = io_output_28_REG;
  assign io_output_29 = io_output_29_REG;
  assign io_output_30 = io_output_30_REG;
  assign io_output_31 = io_output_31_REG;
  assign io_output_32 = io_output_32_REG;
  assign io_output_33 = io_output_33_REG;
  assign io_output_34 = io_output_34_REG;
  assign io_output_35 = io_output_35_REG;
  assign io_output_36 = io_output_36_REG;
  assign io_output_37 = io_output_37_REG;
  assign io_output_38 = io_output_38_REG;
  assign io_output_39 = io_output_39_REG;
  assign io_output_40 = io_output_40_REG;
  assign io_output_41 = io_output_41_REG;
  assign io_output_42 = io_output_42_REG;
  assign io_output_43 = io_output_43_REG;
  assign io_output_44 = io_output_44_REG;
  assign io_output_45 = io_output_45_REG;
  assign io_output_46 = io_output_46_REG;
  assign io_output_47 = io_output_47_REG;
  assign io_output_48 = io_output_48_REG;
  assign io_output_49 = io_output_49_REG;
  assign io_output_50 = io_output_50_REG;
  assign io_output_51 = io_output_51_REG;
  assign io_output_52 = io_output_52_REG;
  assign io_output_53 = io_output_53_REG;
  assign io_output_54 = io_output_54_REG;
  assign io_output_55 = io_output_55_REG;
  assign io_output_56 = io_output_56_REG;
  assign io_output_57 = io_output_57_REG;
  assign io_output_58 = io_output_58_REG;
  assign io_output_59 = io_output_59_REG;
  assign io_output_60 = io_output_60_REG;
  assign io_output_61 = io_output_61_REG;
  assign io_output_62 = io_output_62_REG;
  assign io_output_63 = io_output_63_REG;
endmodule

